name: buf-pull-request
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Install go gRPC plugin
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
      - uses: bufbuild/buf-setup-action@v1
      - name: Generate
        run: |
          buf generate
      - name: Check diff
        id: diff
        run: |
          git add -N .
          git diff --exit-code --quiet
        continue-on-error: true
      - name: Test
        run: |
          echo HEAD:${{ github.head_ref }}
      - name: Commit & Push
        if: steps.diff.outcome == 'failure' # diff がある場合のみ実行する
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m '[ci skip] Generate gRPC code'
          git push origin HEAD:${{ github.head_ref }}
